swagger: '2.0'
info:
  version: 0.7.3
  title: Samnordisk runtextdatabas söktjänst API
  description: >-
    Samnordisk runtextdatabas (SRD) söktjänst API. Specification för
    Riksantikvarieämbetets forskningsplattform för runor inom projektet
    Evighetsrunor. API:et används för att hitta och söka i runtexter i SRD. Sökresultaten innehåller endast grundinformationen om runtexterna (id:n, text och geografiska koordinater). Ytterligare metadata runt runtexterna, bärarobjekt samt kopplad information hämtas via K-SAMSÖK
  contact:
    url: 'https://www.raa.se/kulturarv/runor-och-runstenar/projektet-evighetsrunor/'
    email: toni.thomsson@raa.se
host: uu.se
schemes:
  - https
basePath: /evighetsrunor/api/v1
paths:
  '/signums/{matching_text}':
    get:
      summary: Hämtar lista med signum
      description: >-
        Hämta en lista med signum som kan användas vid enkel sökning (typeahead)
        på signum
      parameters:
        - name: matching_text
          in: path
          required: true
          type: string
          description: Del av signum att matcha mot
      produces:
        - application/json
      responses:
        '200':
          description: En lista med signum
          schema:
            type: array
            example:
              - Öl 4 $
              - Öl Fv1911;274 B $
              - ...
            items:
              type: string
        '500':
          description: (Internal server error). Ett oväntat fel inträffade.
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Enkel sökning
  '/places/{matching_text}':
    get:
      summary: Hämtar lista med platser
      description: >-
        Hämta en lista med platser som kan användas vid enkel sökning
        (typeahead) på plats
      parameters:
        - name: matching_text
          in: path
          required: true
          type: string
          description: Del av namn på plats att matcha mot
      produces:
        - application/json
      responses:
        '200':
          description: En lista med platser
          schema:
            type: array
            example:
              - id: ca79d466-888f-4011-b5bd-35fc6dd1d622
                name: Abrahamstorp
              - id: 25a4de16-c421-41ed-8d17-fc465fd03db1
                name: Ackarby
              - id: b70ec612-cef6-446d-afc0-4e3387804842
                name: ...
            items:
              $ref: '#/definitions/SelectionItem'
        '500':
          description: (Internal server error). Ett oväntat fel inträffade.
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Enkel sökning
  /selection/groups:
    get:
      summary: Hämtar lista med urvalsgrupper
      description: >-
        Hämtar lista med urvalsgrupper att användas när man sätter filtervillkor
        för en avancerad sökning
      produces:
        - application/json
      responses:
        '200':
          description: En lista med urvalsgrupper
          schema:
            type: array
            example:
              - id: 161ab23e-7566-43a0-9dbe-c7f237f27765
                name: Plats
              - id: d3c41141-ef42-4ef3-9cbb-3d49fa6acffe
                name: Socken
              - id: 30ba8d99-f27b-48fc-8048-7892eb3a0fbc
                name: Härrad
              - id: b95dc24b-a1f6-4310-8a9e-3d0264f0f53e
                name: ...
            items:
              $ref: '#/definitions/SelectionGroup'
        '500':
          description: (Internal server error). Ett oväntat fel inträffade.
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Avancerad sökning
  '/selection/{group_id}/{matching_text}':
    get:
      summary: Hämtar lista med urval
      description: >-
        Hämtar lista med urval för en urvalsgrupp att användas när man sätter
        filtervillkor för en avancerad sökning
      produces:
        - application/json
      parameters:
        - name: group_id
          in: path
          required: true
          type: string
          description: Id för urvalsgrupp
        - name: matching_text
          in: path
          required: true
          type: string
          description: Del av namn på urval att matcha mot
      responses:
        '200':
          description: En lista med urval
          schema:
            type: array
            example:
              - id: ca79d466-888f-4011-b5bd-35fc6dd1d622
                name: Abrahamstorp
              - id: 25a4de16-c421-41ed-8d17-fc465fd03db1
                name: Ackarby
              - id: b70ec612-cef6-446d-afc0-4e3387804842
                name: ...
            items:
              $ref: '#/definitions/SelectionItem'
        '404':
          description: (Not found). Gruppen saknas
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              status: 404
              message: Gruppen saknas
              path: /selection/12/test
              timestamp: '1990-12-31T23:59:60Z'
        '500':
          description: (Internal server error). Ett oväntat fel inträffade.
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Avancerad sökning
  /translationtypes:
    get:
      summary: Hämtar alla översättningstyper
      description: Översättningstyper att använda när en sökfråga sätts samman
      produces:
        - application/json
      responses:
        '200':
          description: (OK)  
          schema:
            type: array
            items:
              $ref: '#/definitions/RunicTextTranslationType'
        '500':
          description: (Internal server error). Ett oväntat fel inträffade.
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Avancerad sökning      
  /search:
    get:
      summary: Enkel sökning. Sök efter runtexter med del av plats eller signum
      description: Söker efter runtexter med del av plats eller signum
      produces:
        - application/json
      parameters:
        - name: matching_text
          in: query
          required: true
          type: string
          description: Söksträng
        - name: search_field
          in: query
          required: true
          type: string
          enum:
            - PLACE
            - SIGNUM
          description: Sökfält
      responses:
        '200':
          description: (OK)
          schema:
            type: array
            items:
              $ref: '#/definitions/RunicInscription'
        '500':
          description: (Internal server error). Ett oväntat fel inträffade.
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Enkel sökning
    post:
      summary: Avancerad sökning i runtexter enligt sökvillkor
      description: >-
        Sök i runtexter enligt kombinerade sökvillkor för text samt filtrering
        enligt urval
      parameters:
        - name: query
          in: body
          required: true
          schema:
            $ref: '#/definitions/SearchQuery'
      responses:
        '200':
          description: Hittade runtexter med markering av hittade ord
          schema:
            type: array
            items:
              $ref: '#/definitions/SearchResult'
        '500':
          description: (Internal server error). Ett oväntat fel inträffade.
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Avancerad sökning
  /map:
    get:
      summary: Hämtar alla geografiska punkter 
      description: Hämtar alla geografiska punkter där runinskriptioner finns eller har hittats
      produces:
        - application/json
      responses:
        '200':
          description: (OK). Poster hittades
          schema:
            type: array
            items:
              $ref: '#/definitions/RunicInscriptionGeoPosition'
        '500':
          description: (Internal server error). Ett oväntat fel inträffade.
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Karta  
  
  '/inscription/{id}':
    get:
      summary: Hämtar en runinskrift med hjälp av signum eller URI
      description: Hämtar en runinskrift med hjälp av signum eller URI
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: Signum eller URI
      responses:
        '200':
          description: (OK). Post hittades
          schema:
            $ref: '#/definitions/RunicInscription'
        '404':
          description: (Not found). Ingen träff
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              status: 404
              message: Signum eller URI saknas
              path: /selection/12/test
              timestamp: '1990-12-31T23:59:60Z'
        '500':
          description: (Internal server error). Ett oväntat fel inträffade.
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Entiteter
definitions:
  SearchQuery:
    description: Sökfråga som används för att sätta sökvillkor vid avancerad sökning i SRD
    type: object
    required:
      - query
    properties:
      query:
        description: Textsökfråga
        type: array
        items:
          $ref: '#/definitions/TextQueryGroup'
      filter:
        description: Filtrering
        type: array
        items:
          $ref: '#/definitions/Selection'
  TextQueryGroup:
    description: Gruppering (tänk parenteser) av sökvillkor i en avancerad sökfråga
    type: object
    required:
      - group
    properties:
      logic_operator:
        description: >-
          Anger logisk operator för användas när flera sökfrågor kombineras. Första
          frågan i en TextQueryGroup behöver inte ha en logisk operator
        type: string
        enum:
          - AND
          - OR
          - NOT
      group:
        type: array
        items:
          $ref: '#/definitions/TextQuery'
  TextQuery:
    description: Sökfråga som används för att sätta villkor för textsökning i SRD
    type: object
    required:
      - matching_text
      - proper_name_search
      - translation
    properties:
      logic_operator:
        description: >-
          Anger logisk operator för användas när flera sökfrågor kombineras. Första
          frågan i en TextQuery behöver inte ha en logisk operator
        type: string
        enum:
          - AND
          - OR
          - NOT
      matching_text:
        description: Söktext
        example: þaiR
        type: string
      proper_name_search:
        description: Anger hur/om sökning skall ske i egennamn
        type: string
        enum:
          - INCLUDE
          - EXCLUDE
          - ONLY
      translation_type_id:
        description: Anger i vilken översättning sökningen skall ske
        example: da0b20c8-e036-456b-8f0a-6aeb06105f9a
        type: string
  SearchResult:
    description: Resultat av en sökfråga
    type: object
    required:
      - inscription
      - marked_words_index
    properties:
      inscription:
        description: Runinskrifter
        type: array
        items:
          $ref: '#/definitions/RunicInscription'
      found_words_index:
        type: array
        example:
          - 0
          - 4
          - 6
        items:
          type: integer
  RunicInscription:
    description: Grundinformation för en runinskription
    type: object
    required:
      - signum
      - uri
      - translation
      - geo_position
    properties:
      signum:
        description: Signum
        example: Öl 4 $
        type: string
      alt_signum:
        description: Alternativt signum
        type: array
        example:
          - B 1063
          - L 1318
          - ...
        items:
          type: string
      uri:
        description: Persistent identifierare för runinskriften (används för att hämta information från K-SAMSÖK)
        example: >-
          https://kulturarvsdata.se/objekt/runtext/d778ec61-8f70-4105-ba93-e928328173e2
        type: string
      object_uri:
        description: Persistent identifierare för bärare av runinskriften (används för att hämta information från K-SAMSÖK)
        example: >-
          https://kulturarvsdata.se/objekt/lamning/7b70c89a-c191-4d73-4455fd5dd2a7
        type: string
      translation:
        description: Översättning av runtext
        type: array
        items:
          $ref: '#/definitions/RunicTextTranslation'
      position:
        $ref: '#/definitions/RunicInscriptionGeoPosition'
  RunicTextTranslation:
    description: En transliterering/normalisering/översättning av en runtext
    type: object
    required:
      - text
      - translation
    properties:
      text:
        description: Runtext
        example: ...-abi · þaiR --tu · raisa · stein- · eftiR · rantui · moþor sina
        type: string
      translation_type:
        $ref: '#/definitions/RunicTextTranslationType'
  RunicTextTranslationType:
    description: Översättningstyp, transliterering/normalisering/översättning av en runtext
    type: object
    required:
      - id
      - name
      - proper_name_searchable
      - is_complete
    properties:
      id:
        description: Id för översättningstypen
        example: da0b20c8-e036-456b-8f0a-6aeb06105f9a
        type: string
      name:
        description: Namn på översättningstypen
        example: Fornvästnordiska
        type: string
      proper_name_searchable:
        description: Anger om texter av denna översättningstyp har sökbara egennamn
        example: true
        type: boolean
      is_complete:
        description: Anger om texter av denna översättningstyp är kompletta
        example: true
        type: boolean  
  RunicInscriptionGeoPosition:
    description: Geografiska positioner med nuvarande och ev. ursprungligt läge att rendera på en bakgrundskarta
    type: object
    required:
      - signum
      - uri
      - current
    properties:
      signum:
        description: Signum
        example: Öl 4 $
        type: string
      uri:
        description: Persistent identifierare för runinskriften
        example: https://kulturarvsdata.se/objekt/runtext/d778ec61-8f70-4105-ba93-e928328173e2
      current:
        $ref: '#/definitions/Geometry'
      orginal:
        $ref: '#/definitions/Geometry'
  SelectionGroup:
    description: 'Urvalsgrupp (tex socken, härrad eller kommun)'
    type: object
    required:
      - id
      - name
      - items
    properties:
      id:
        description: Identitet för urvalsgruppen
        example: b86b72cb-bc22-45fc-90cb-eaf213d3aaf9
        type: string
      name:
        description: Namn på urvalsgruppen
        example: Socken
        type: string
  SelectionItem:
    description: Ett urval (tex socken Bro)
    type: object
    required:
      - id
      - name
    properties:
      id:
        description: Identitet för urvalet
        example: c387aad1-9b4b-4c8c-ad0d-0bb4eaf605d6
        type: string
      name:
        description: Namn på urval
        example: Bro
        type: string
  Selection:
    description: Kompletterande filter med urvalsgrupper
    type: object
    required:
      - logic_operator
      - item
    properties:
      logic_operator:
        description: Logisk operator att användas när filter kombineras
        type: string
        enum:
          - AND
          - NOT
      item:
        $ref: '#/definitions/SelectionItem'
  Geometry:
    description: >-
      Geometrier uttryckta i geoJSON formatet och benämns som GeoJSON[2008]. Se
      specifikationen http://geojson.org/.


      TODO Vilket koordinatsystem skall vi använda? SR-ORG:7483 EPSG:3857 --
      WGS84 Web Mercator (Auxiliary Sphere) för att visa på Google-maps?
    type: object
    required:
      - type
      - coordinates
    properties:
      type:
        type: string
        enum:
          - Point
          - Linestring
          - Polygon
        example: Point
      crs:
        type: object
        required:
          - type
        properties:
          type:
            type: string
            enum:
              - name
          properties:
            type: object
            required:
              - name
            properties:
              name:
                description: Anger koordinatsystemet för geometrierna
                type: string
                example: 'EPSG:3857'
      coordinates:
        additionalProperties: true
        type: array
        items:
          type: array
          items:
            type: array
            example:
              - 57.6353939
              - 18.2954135
            items:
              type: number
  Error:
    description: Ett fel
    type: object
    required:
      - status
      - message
      - path
      - timestamp
    properties:
      status:
        type: integer
        example: 500
        description: Http statuskod
      message:
        type: string
        example: 'Tekniskt fel, försök senare'
        description: Innehåller ett felmeddelande tänkt att presenteras för slutanvändare
      exception:
        type: string
        example: java.lang.NullPointerException
        description: Innehåller ett felmeddelande tänkt för tekniker vid felsökning
      path:
        type: string
        example: /selection/13/Test
        description: Anger den resourcepath där felet uppstod
      timestamp:
        type: string
        example: '1990-12-31T23:59:60Z'
        format: dateTime
        description: >-
          Anger tidpunkten när felet inträffade. Tidpunkt angiven som date-time,
          se RFC3339 (Internet Date/Time Format)
